#!/usr/bin/env bash
# quality.sh — format check + build + test + coverage, run from the solution root.
#
# Coverage is COLLECTED and PRINTED here. The gate that FAILS the build when
# coverage drops below the CLAUDE.md thresholds (>=80% domain, >=60% overall)
# is feature 34 (sonarqube_quality_gates, phase 21) — see CLAUDE.md's testing
# conventions ("Coverage gates ... verified to fail when breached"). Until
# that feature lands, do NOT fake a gate that does not gate: this script
# reports a number, it does not enforce one.
#
# Exit codes: 0 = format clean + build succeeded + all tests passed, for the
#             .NET solution AND apps/web.
#             non-zero = the first failing step's exit code.
#
# QUALITY_ONLY=web ./quality.sh runs only section 6 (apps/web) — the switch
# exists so each web gate can be armed without a 30-minute .NET run in
# between. Unset (the default), every section runs.

set -u

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[0;33m'; BLUE='\033[0;34m'; NC='\033[0m'
ok()      { printf "${GREEN}[OK]${NC}    %s\n" "$1"; }
info()    { printf "${BLUE}[INFO]${NC}  %s\n" "$1"; }
warn()    { printf "${YELLOW}[WARN]${NC}  %s\n" "$1"; }
fail()    { printf "${RED}[FAIL]${NC}  %s\n" "$1"; }
section() { printf "\n${BLUE}── %s ${NC}\n" "$1"; }

cd "$(dirname "$0")" || exit 1

SLN="OrderToCash.sln"
COVERAGE_DIR="./TestResults"
QUALITY_ONLY="${QUALITY_ONLY:-}"

if [ -n "$QUALITY_ONLY" ] && [ "$QUALITY_ONLY" != "web" ]; then
  fail "QUALITY_ONLY must be empty or 'web' (got '$QUALITY_ONLY')"
  exit 2
fi

if [ "$QUALITY_ONLY" = "web" ]; then
  warn "QUALITY_ONLY=web — skipping the .NET sections 1-5"
else

# ─────────────────────────────────────────────────────────────
section "1. Format check"

if dotnet format "$SLN" --verify-no-changes; then
  ok "dotnet format --verify-no-changes: clean"
else
  fail "dotnet format found unformatted files — run 'dotnet format $SLN' and re-commit"
  exit 1
fi

# ─────────────────────────────────────────────────────────────
section "2. Build"

if dotnet build "$SLN" --nologo; then
  ok "dotnet build: succeeded"
else
  fail "dotnet build failed"
  exit 1
fi

# ─────────────────────────────────────────────────────────────
section "3. Test + coverage"

rm -rf "$COVERAGE_DIR"

if dotnet test "$SLN" --nologo --collect:"XPlat Code Coverage" --results-directory "$COVERAGE_DIR"; then
  ok "dotnet test: all tests passed"
else
  TEST_EXIT=$?
  fail "dotnet test failed"
  exit "$TEST_EXIT"
fi

# ─────────────────────────────────────────────────────────────
section "4. Coverage summary"

REPORT_FOUND=0
while IFS= read -r -d '' report; do
  REPORT_FOUND=1
  LINE_RATE="$(grep -oE 'line-rate="[0-9.]+"' "$report" | head -1 | grep -oE '[0-9.]+')"
  if [ -n "${LINE_RATE:-}" ]; then
    PCT="$(awk -v r="$LINE_RATE" 'BEGIN { printf "%.1f", r * 100 }')"
    info "coverage report: $report — line coverage ${PCT}%"
  else
    warn "coverage report found but line-rate could not be parsed: $report"
  fi
done < <(find "$COVERAGE_DIR" -name "coverage.cobertura.xml" -print0 2>/dev/null)

if [ "$REPORT_FOUND" -eq 0 ]; then
  warn "no coverage.cobertura.xml produced under $COVERAGE_DIR — coverlet.collector may not be wired into every test project"
fi

# ─────────────────────────────────────────────────────────────
section "5. Coverage gate (>=80% domain layer, >=60% overall)"

# Mechanism (feature 34 — sonarqube_quality_gates, phase 21): every test
# project here uses coverlet.collector ("--collect:XPlat Code Coverage" in
# section 3 above), not coverlet.msbuild, so there is no per-project
# build-time /p:Threshold= to lean on. coverlet.collector also instruments
# whatever assemblies happen to load into each test host, so a single
# project's coverage.cobertura.xml under-reports a class exercised by a
# SIBLING test project (e.g. Orders/Domain/*.cs shows partial coverage under
# Orders.UnitTests alone, because Orders.IntegrationTests covers different
# lines of the same files). A correct gate therefore MERGES every report
# already produced by section 3, per (filename, line number), taking a line
# as covered if ANY report hit it — not merely averaging each report's own
# line-rate, which would double-count some lines and miss others' union.
#
# Domain layer = every .cs file whose path contains "/Domain/" across all
# seven services with a Domain/ folder (Billing, Fulfillment, Gateway,
# Notifications, Orders, Projector, Seed — confirmed by `find src/*/Domain
# -type d`; Seed's own Domain/ holds its deterministic seed-data/fixture
# model, not a saga, but it is still a Domain/ folder under CLAUDE.md's
# Clean Architecture per service). Overall = every .cs file under src/ that
# produced a class entry in any report.
#
# EF Core migration scaffolding (*/Migrations/*.cs, *ModelSnapshot.cs) is
# excluded from BOTH gates: it is machine-generated by `dotnet ef migrations
# add`, never hand-written, and chasing coverage on it buys nothing — the
# same principle #7's sonar-project.properties applies to its own generated
# code (packages/contracts/src/generated/**). Projector's
# TimelineOrderMigration.cs is hand-written application code despite the
# name and is NOT excluded (it lives directly under Infrastructure/
# Persistence/, not a Migrations/ directory, and does not end in
# ModelSnapshot.cs).

DOMAIN_THRESHOLD=80.0
OVERALL_THRESHOLD=60.0

if [ "$REPORT_FOUND" -eq 0 ]; then
  fail "no coverage.cobertura.xml produced under $COVERAGE_DIR — the coverage gate cannot run"
  exit 1
fi

GATE_OUTPUT="$(python3 - "$COVERAGE_DIR" "$DOMAIN_THRESHOLD" "$OVERALL_THRESHOLD" <<'PY'
import glob
import os
import sys
import xml.etree.ElementTree as ET

coverage_dir, domain_threshold, overall_threshold = (
    sys.argv[1],
    float(sys.argv[2]),
    float(sys.argv[3]),
)

# filename (normalised, relative to src/) -> { line_number: covered_bool }
lines_by_file: dict[str, dict[int, bool]] = {}

reports = sorted(
    glob.glob(os.path.join(coverage_dir, "**", "coverage.cobertura.xml"), recursive=True)
)
if not reports:
    print("NO_REPORTS")
    sys.exit(1)

for report_path in reports:
    root = ET.parse(report_path).getroot()
    for cls in root.iter("class"):
        filename = cls.get("filename")
        if not filename:
            continue
        norm = filename.replace("\\", "/")
        if "/Migrations/" in norm or norm.endswith("ModelSnapshot.cs"):
            continue
        bucket = lines_by_file.setdefault(norm, {})
        for line_el in cls.iter("line"):
            number = int(line_el.get("number"))
            hits = int(line_el.get("hits", "0"))
            bucket[number] = bucket.get(number, False) or (hits > 0)

domain_total = domain_covered = 0
overall_total = overall_covered = 0

for filename, linemap in lines_by_file.items():
    total = len(linemap)
    covered = sum(1 for v in linemap.values() if v)
    overall_total += total
    overall_covered += covered
    if "/Domain/" in filename:
        domain_total += total
        domain_covered += covered


def pct(covered: int, total: int) -> float:
    return (covered / total * 100.0) if total else 100.0


domain_pct = pct(domain_covered, domain_total)
overall_pct = pct(overall_covered, overall_total)

print(f"DOMAIN {domain_covered} {domain_total} {domain_pct:.2f}")
print(f"OVERALL {overall_covered} {overall_total} {overall_pct:.2f}")

failed = False
if domain_pct < domain_threshold:
    print(
        f"GATE_FAIL domain layer coverage {domain_pct:.2f}% "
        f"({domain_covered}/{domain_total} lines) is below the required "
        f"{domain_threshold:.1f}% threshold"
    )
    failed = True
if overall_pct < overall_threshold:
    print(
        f"GATE_FAIL overall coverage {overall_pct:.2f}% "
        f"({overall_covered}/{overall_total} lines) is below the required "
        f"{overall_threshold:.1f}% threshold"
    )
    failed = True

sys.exit(1 if failed else 0)
PY
)"
GATE_EXIT=$?

while IFS= read -r gate_line; do
  case "$gate_line" in
    DOMAIN\ *)
      set -- $gate_line
      info "domain layer coverage: ${4}% (${2}/${3} lines) — threshold >=${DOMAIN_THRESHOLD}%"
      ;;
    OVERALL\ *)
      set -- $gate_line
      info "overall coverage: ${4}% (${2}/${3} lines) — threshold >=${OVERALL_THRESHOLD}%"
      ;;
    GATE_FAIL\ *)
      fail "${gate_line#GATE_FAIL }"
      ;;
    NO_REPORTS)
      fail "coverage gate: no coverage.cobertura.xml found by the merge step"
      ;;
  esac
done <<EOF
$GATE_OUTPUT
EOF

if [ "$GATE_EXIT" -ne 0 ]; then
  fail "coverage gate FAILED — see the [FAIL] line(s) above for which layer and by how much"
  exit "$GATE_EXIT"
else
  ok "coverage gate passed (domain >=${DOMAIN_THRESHOLD}%, overall >=${OVERALL_THRESHOLD}%)"
fi

fi # QUALITY_ONLY

# ─────────────────────────────────────────────────────────────
section "6. Web app (apps/web)"

# Each step is a gate that has been seen to FAIL on a planted violation
# (progress/impl_web_app.md, "Quality-gate arming"). #7's web lint exited 0
# while linting zero component files, so `pnpm lint` also runs
# scripts/lint-coverage.mjs, which fails when any source file escapes the config.
# Web coverage is reported, not enforced — the same rule as section 4.
WEB_DIR="./apps/web"
if ! command -v pnpm >/dev/null 2>&1; then
  fail "pnpm is not installed — apps/web cannot be checked (corepack enable, see .nvmrc)"
  exit 1
fi

web_step() {
  local label="$1"; shift
  info "apps/web: $label"
  if (cd "$WEB_DIR" && "$@"); then
    ok "apps/web: $label"
  else
    local code=$?
    fail "apps/web: $label failed (exit $code)"
    exit "$code"
  fi
}

web_step "install (frozen lockfile)" pnpm install --frozen-lockfile --reporter=append-only
web_step "OpenAPI types match specs/shared/openapi.yaml" pnpm run --silent types:check
web_step "lint (+ every source file linted)" pnpm run --silent lint
web_step "typecheck" pnpm run --silent typecheck
web_step "unit + component tests (Vitest), with coverage" pnpm run --silent test:coverage
if [ -f "$WEB_DIR/coverage/coverage-summary.json" ]; then
  WEB_LINES="$(node -e 'const s=require(process.argv[1]).total.lines;console.log(s.pct)' "$WEB_DIR/coverage/coverage-summary.json")"
  info "apps/web line coverage ${WEB_LINES}%"
fi
web_step "production build" env NEXT_TELEMETRY_DISABLED=1 pnpm run --silent build
web_step "integration tests against the production build" pnpm run --silent test:integration

ok "quality.sh finished"
