// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderToCash.Fulfillment.Infrastructure.Persistence;

#nullable disable

namespace OrderToCash.Fulfillment.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FulfillmentDbContext))]
    [Migration("20260901103111_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrderToCash.Fulfillment.Infrastructure.Persistence.Entities.Despatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("company_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DespatchDate")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("despatch_date");

                    b.Property<string>("DespatchReference")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("despatch_reference");

                    b.Property<string>("OrderReference")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("order_reference");

                    b.Property<string>("RetailerCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("retailer_code");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DespatchReference")
                        .IsUnique();

                    b.HasIndex("OrderReference")
                        .IsUnique();

                    b.ToTable("despatches", (string)null);
                });

            modelBuilder.Entity("OrderToCash.Fulfillment.Infrastructure.Persistence.Entities.DespatchItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DespatchId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("despatch_id");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("product_code");

                    b.Property<int>("Units")
                        .HasColumnType("int")
                        .HasColumnName("units");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DespatchId");

                    b.ToTable("despatch_items", (string)null);
                });

            modelBuilder.Entity("OrderToCash.Fulfillment.Infrastructure.Persistence.Entities.DespatchNumberSequence", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("NextValue")
                        .HasColumnType("int")
                        .HasColumnName("next_value");

                    b.HasKey("Id");

                    b.ToTable("despatch_number_sequences", (string)null);
                });

            modelBuilder.Entity("OrderToCash.Fulfillment.Infrastructure.Persistence.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("aggregate_id");

                    b.Property<Guid>("CausationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("causation_id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("published_at");

                    b.Property<long>("Seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("seq");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Seq"));

                    b.Property<string>("TraceParent")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("trace_parent");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("Seq")
                        .IsUnique();

                    b.HasIndex("PublishedAt", "OccurredAt");

                    b.HasIndex("PublishedAt", "Seq");

                    b.ToTable("outbox", (string)null);
                });

            modelBuilder.Entity("OrderToCash.Fulfillment.Infrastructure.Persistence.Entities.ProcessedEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Consumer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("consumer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("event_id");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("processed_at");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "Consumer")
                        .IsUnique();

                    b.ToTable("processed_events", (string)null);
                });

            modelBuilder.Entity("OrderToCash.Fulfillment.Infrastructure.Persistence.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("company_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at");

                    b.Property<string>("OrderReference")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("order_reference");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("product_code");

                    b.Property<string>("RetailerCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("retailer_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("StockId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("stock_id");

                    b.Property<int>("Units")
                        .HasColumnType("int")
                        .HasColumnName("units");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("StockId");

                    b.HasIndex("OrderReference", "Status");

                    b.ToTable("reservations", (string)null);
                });

            modelBuilder.Entity("OrderToCash.Fulfillment.Infrastructure.Persistence.Entities.Stock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("company_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at");

                    b.Property<int>("LowStockThreshold")
                        .HasColumnType("int")
                        .HasColumnName("low_stock_threshold");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("product_code");

                    b.Property<int>("ReservedUnits")
                        .HasColumnType("int")
                        .HasColumnName("reserved_units");

                    b.Property<int>("Units")
                        .HasColumnType("int")
                        .HasColumnName("units");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CompanyCode", "ProductCode")
                        .IsUnique();

                    b.ToTable("stock", (string)null);
                });

            modelBuilder.Entity("OrderToCash.Fulfillment.Infrastructure.Persistence.Entities.DespatchItem", b =>
                {
                    b.HasOne("OrderToCash.Fulfillment.Infrastructure.Persistence.Entities.Despatch", null)
                        .WithMany()
                        .HasForeignKey("DespatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrderToCash.Fulfillment.Infrastructure.Persistence.Entities.Reservation", b =>
                {
                    b.HasOne("OrderToCash.Fulfillment.Infrastructure.Persistence.Entities.Stock", null)
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
